--장르가 액셔닌 비디오 테잎을 예약한 고객의 이름
SELECT NAME
FROM CUSTOMER C, VIDEO V, RESERVED R
WHERE C.CUSTOMER_ID = R.CUSTOMER_ID AND C.VIDEO_ID = R.VIDEO_ID AND UPPER(GENRE) = 'ACTION';

-- 장르가 액션인 비디오 테잎을 모두 예약한 고객의 이름
SELECT NAME
FROM CUSTOMER C
WHERE NOT EXISTS
(SELECT VIDEO_ID
FROM VIDEO
WHERE UPPER(GENRE) = 'ACTION')
MINUS
(SELECT VIDEO_ID
FROM RESERVED
WHERE CUSTOMER_ID = C.CUSTOMER_ID);