ALTER TABLE VIDEO
MODIFY (TITLE CHAR(30));

INSERT INTO CUSTOMER VALUES(1, 'John', '123 Main St', '555-1234');
INSERT INTO CUSTOMER VALUES(2, 'Jane', '456 Oak St', '555-5678');
INSERT INTO CUSTOMER VALUES(3, 'Bob', '789 Pine St', '555-9012');
INSERT INTO CUSTOMER VALUES(4, 'Alice', '321 Elm St', '555-3456');
INSERT INTO CUSTOMER VALUES(5, 'Charlie', '987 Maple St', '555-7890');

INSERT INTO VIDEO VALUES(1, 'The Lord of the Rings', 'Fantasy');
INSERT INTO VIDEO VALUES(2, 'The Matrix', 'Sci-Fi');
INSERT INTO VIDEO VALUES(3, 'Titanic', 'Romance');
INSERT INTO VIDEO VALUES(4, 'The Shawshank Redemption', 'Drama');
INSERT INTO VIDEO VALUES(5, 'Jurassic Park', 'Action');
INSERT INTO VIDEO VALUES(6, 'Planet Earth', 'Documentary');

INSERT INTO RESERVED VALUES(1, 1, '2023-11-23');
INSERT INTO RESERVED VALUES(2, 3, '2023-11-24');
INSERT INTO RESERVED VALUES(3, 2, '2023-11-25');
INSERT INTO RESERVED VALUES(4, 4, '2023-11-26');
INSERT INTO RESERVED VALUES(5, 5, '2023-11-27');
INSERT INTO RESERVED VALUES(1, 2, '2023-11-28');
INSERT INTO RESERVED VALUES(2, 4, '2023-11-29');
INSERT INTO RESERVED VALUES(3, 5, '2023-11-30');
INSERT INTO RESERVED VALUES(4, 1, '2023-12-01');
INSERT INTO RESERVED VALUES(5, 3, '2023-12-02');

--질의1: 제목이 '반지의 제왕'인 비디오 테이프의 장르를 검색하라
SELECT GENRE
FROM VIDEO
WHERE TITLE = 'The Lord of the Rings';

--질의2: 예약된 비디오 테이프의 id를 검색하라
SELECT VIDEO_ID
FROM RESERVED;

--질의3: 예약되지 않은 비디오 테이프의 id를 검색하라
SELECT VIDEO_ID
FROM VIDEO
WHERE VIDEO_ID NOT IN
(SELECT V.VIDEO_ID
FROM RESERVED R, VIDEO V
WHERE V.VIDEO_ID = R.VIDEO_ID);

--질의4: 예약된 모든 비디오 테이프의 제목을 검색하라
SELECT TITLE
FROM RESERVED R, VIDEO V
WHERE V.VIDEO_ID = R.VIDEO_ID;

--질의5: 비디오 테이프를 예약한 고객의 이름을 검색하라
SELECT TITLE
FROM RESERVED R, VIDEO V
WHERE V.VIDEO_ID = R.VIDEO_ID;

--질의6: 장르가 '액션'인 비디오 테이프를 예약한 고객의 주소를 검색하라
SELECT ADDRESS
FROM RESERVED R, CUSTOMER C, VIDEO V
WHERE C.CUSTOMER_ID = R.CUSTOMER_ID AND V.VIDEO_ID = R.VIDEO_ID AND GENRE = 'Action';

--질의7: 장르가 '다큐멘터리'인 비디오 테이프를 모두 예약한 고객의 이름을 검색하라.
SELECT NAME
FROM RESERVED R, CUSTOMER C, VIDEO V
WHERE C.CUSTOMER_ID = R.CUSTOMER_ID AND V.VIDEO_ID = R.VIDEO_ID AND GENRE = 'Documentary';








