-- 질의 1 : 가장 오래 근무한 사원에 관한 모든 데이터를 검색하라.
SELECT *
FROM EMPLOYEE
ORDER BY HIREDATE
FETCH FIRST 1ROW ONLY;

-- 질의 2 : 최종철과 같은 부서에 근무하는 사원에 관한 모든 데이터를 검색하라.
SELECT *
FROM EMPLOYEE
WHERE DNO = 
(SELECT DNO
FROM EMPLOYEE
WHERE EMPNAME = '최종철');

-- 질의 3 : 회사의 전체 사원 수를 검색하라
SELECT COUNT(*)
FROM EMPLOYEE;

-- 질의 4 : 회사에 몇  개의 부서가 있는가를 검색하라
SELECT COUNT(*)
FROM DEPARTMENT;

-- 질의 5 : 기획부에 근무하는 사원들의 이름과 직급을 검색하라.
SELECT EMPNAME, TITLE
FROM EMPLOYEE, DEPARTMENT
WHERE DNO = DEPTNO AND DEPTNAME = '기획';

-- 질의 6 : 한 명 이상의 사원이 근무하는 부서의 개수를 검색하라
SELECT COUNT(DISTINCT DEPTNO)
FROM DEPARTMENT, EMPLOYEE
WHERE DNO = DEPTNO
GROUP BY DEPTNO
HAVING COUNT(EMPNO) > 1;

-- 질의 7 : 사원이 한 명도 근무하지 않는 부서를 검색하라
SELECT DEPTNAME
FROM DEPARTMENT
WHERE NOT EXISTS 
(SELECT *
FROM EMPLOYEE
WHERE DNO = DEPTNO
)

-- 질의 8 : 사원이 한 명 이상 속한 부서에 대해서 평균 급여를 검색하라.
SELECT AVG(SALARY)
FROM EMPLOYEE, DEPARTMENT
WHERE DNO = DEPTNO
GROUP BY DEPTNO
HAVING COUNT(EMPNO) > 1;

-- 질의 9 : 부서에 속한 사원들의 평균 급여가 가장 많은 부서의 이름과 평균 급여를 검색하라.
SELECT DEPTNAME, AVG(SALARY)
FROM EMPLOYEE, DEPARTMENT
WHERE DNO = DEPTNO
GROUP BY DEPTNAME
ORDER BY AVG(SALARY)
FETCH FIRST 1ROW ONLY;

-- 질의 10 : EMPLOYEE와 DEPARTMENT 릴레이션을 조인하고, 부서번호 순서에 따라 정렬하라
SELECT *
FROM EMPLOYEE, DEPARTMENT
WHERE DNO = DEPTNO
ORDER BY DNO;

-- 질의 11 : 모든 사원들을 직급별로 그룹화하고, 각 그룹별 사원 수와 평균 급여를 검색하라.
SELECT TITLE, COUNT(*), AVG(SALARY)
FROM EMPLOYEE
GROUP BY TITLE;

-- 질의 12 : 모든 사원들을 직급별로 그룹화하고, 동일 직급을 갖는 사원 수가 2명 이상인 직급에 대해서 직급, 사원 수, 연간 급여를 검색하라. 
SELECT TITLE, COUNT(*), SUM(SALARY)*12 AS ANNUAL_SALARY
FROM EMPLOYEE
GROUP BY TITLE
HAVING COUNT(*) >= 2;

-- 질의 13 : 직급이 대리인 사원이 적어도 2명 이상 속한 부서의 이름을 검색하라
SELECT DEPTNAME
FROM EMPLOYEE, DEPARTMENT
WHERE DNO = DEPTNO AND TITLE = '대리'
GROUP BY DEPTNAME
HAVING COUNT(*) >= 2;

-- 질의 14 : 모든 부서에 대해서 이름, 층, 각 부서에 근무하는 사원 수를 검색하라. 사원이 없는 부서도 포함시켜라
SELECT DEPTNAME, FLOOR, COUNT(EMPNO)
FROM DEPARTMENT
LEFT JOIN EMPLOYEE ON DEPTNO = DNO
GROUP BY DEPTNAME, FLOOR;

-- 질의 15 : 부서 1, 2, 3에 공통으로 있는 직급을 검색하라.
SELECT TITLE
FROM DEPARTMENT, EMPLOYEE
WHERE DEPTNO = DNO 
GROUP BY TITLE
HAVING COUNT(DISTINCT DEPTNO)=3;

-- 질의 16 : 개발부서에 근무하는 사원들의 직급과 직급별 사원 수를 검색하라. 사원 수가 많은 직급부터 표시하라.
SELECT TITLE, COUNT(EMPNO)
FROM DEPARTMENT, EMPLOYEE
WHERE DEPTNO = DNO 
GROUP BY TITLE
ORDER BY COUNT(EMPNO) DESC;

-- 질의 17 : 평균 급여가 가장 높은 부서의 부서번호와 이 부서의 최저 급여를 검색하라.
SELECT DNO, MIN(SALARY)
FROM EMPLOYEE
GROUP BY DNO
ORDER BY AVG(SALARY) DESC
FETCH FIRST 1 ROW ONLY;

-- 질의 18 : 소속 사원 수가 4명 이하인 부서의 이름과 사원 수를 검색하라.
SELECT DEPTNAME, COUNT(EMPNO)
FROM EMPLOYEE, DEPARTMENT
WHERE DNO = DEPTNO
GROUP BY DEPTNAME
HAVING COUNT(EMPNO) <= 4;

-- 질의 19 : 자신이 속한 부서의 평균 급여보다 많이 받는 사원의 이름, 부서번호, 급여를 검색하라 (자신을 김창섭이라 가정)
SELECT EMPNAME, SALARY, DNO
FROM EMPLOYEE
WHERE SALARY > 
(SELECT AVG(SALARY)
FROM EMPLOYEE
GROUP BY DNO
HAVING DNO = 
(SELECT DNO
FROM EMPLOYEE
WHERE EMPNAME = '김창섭'
)
);

-- 질의 20 : 각 부서에서 가장 많은 급여를 받는 사원들의 이름, 급여, 부서번호를 검색하라.
SELECT EMPNAME, SALARY, DNO
FROM EMPLOYEE
WHERE (DNO, SALARY) IN (
SELECT DNO, MAX(SALARY)
FROM EMPLOYEE
GROUP BY DNO
);

--질의 21 : 모든 사원에 대해서 사원번호, 이름, 급여, 부서번호, 소속 부서의 평균 급여를 검색하라.
SELECT
    E.EMPNO, E.EMPNAME, E.SALARY, E.DNO, D.AVG_SALARY
FROM EMPLOYEE E
JOIN (
    SELECT DNO, AVG(SALARY) AS AVG_SALARY
    FROM EMPLOYEE
    GROUP BY DNO
) D ON E.DNO = D.DNO;

--질의 22 :  최종철 또는 이수민과 같은 직급을 가진 모든 사원에 대해서 사원의 이름과 직급을 검색하라.
SELECT EMPNAME, TITLE
FROM EMPLOYEE
WHERE TITLE = (SELECT TITLE FROM EMPLOYEE WHERE EMPNAME = '최종철') OR TITLE = (SELECT TITLE FROM EMPLOYEE WHERE EMPNAME = '이수민')
ORDER BY TITLE;












-- 질의 23 : 기획 또는 총무 부서에 근무하지 않는 모든 사원들의 이름을 검색하라.
SELECT EMPNAME
FROM DEPARTMENT, EMPLOYEE
WHERE DNO = DEPTNO AND DEPTNAME NOT IN ('기획', '총무');


-- 질의 24 : DEPARTMENT 릴레이션에 투플 (5, '홍보', 8)을 삽입하라
INSERT INTO DEPARTMENT VALUES (5, '홍보', 8)

-- 질의 25 : EMPLOYEE 릴레이션에서 부서번호 3에 근무하는 사원들을 삭제하라
SELECT CONSTRAINT_NAME, DELETE_RULE
FROM USER_CONSTRAINTS
WHERE TABLE_NAME = 'EMPLOYEE' AND CONSTRAINT_TYPE = 'R';

ALTER TABLE EMPLOYEE
DROP CONSTRAINT SYS_C007460;

ALTER TABLE EMPLOYEE
ADD CONSTRAINT MYCONSTRAINT0001
FOREIGN KEY (MANAGER)
REFERENCES EMPLOYEE(EMPNO)
ON DELETE SET NULL;

DELETE FROM EMPLOYEE WHERE DNO = 3;














